REM this file location is specific to my machine, sorry...
REM this batch file creates templates for documenting my custom nodes!!
"C:\Program Files (x86)\Steam\steamapps\common\Godot Engine\godot.windows.opt.tools.64.exe" --headless --editor --doctool . --gdextension-docs