:: generated by grok!!!
@echo off

pushd "%~dp0.." >nul
set "PROJECT_ROOT=%CD%"
popd >nul

set "BIN_DIR=%PROJECT_ROOT%\bin"
set "CPP_DIR=%PROJECT_ROOT%\cpp"

if exist "%BIN_DIR%" (
    echo Cleaning generated files in bin...
    for /r "%BIN_DIR%" %%F in (
        *.exp *.lib *.pdb *.dll *.so *.a *.o *.obj *.obj.import *.idb *.ilk *.ipdb *.tlog *.log *.tmp
    ) do del /f /q "%%~fF" 2>nul
)

if exist "%CPP_DIR%" (
    echo Cleaning generated files in cpp...
    for /r "%CPP_DIR%" %%F in (
        *.exp *.lib *.pdb *.dll *.so *.a *.o *.obj *.obj.import *.uid *.idb *.ilk *.ipdb *.tlog *.log *.tmp
    ) do del /f /q "%%~fF" 2>nul
)

echo Cleanup complete.