#!/usr/bin/env python
import os
import sys

env = SConscript("godot-cpp/SConstruct")

# For reference:
# - CCFLAGS are compilation flags shared between C and C++
# - CFLAGS are for C-specific compilation flags
# - CXXFLAGS are for C++-specific compilation flags
# - CPPFLAGS are for pre-processor flags
# - CPPDEFINES are for pre-processor defines
# - LINKFLAGS are for linking flags

# tweak this if you want to use different folders, or more folders, to store your source code in.
# overall this searches ./cpp/src/ for all .cpp files...
env.Append(CPPPATH=["src/"])
sources = Glob("src/*.cpp")

# compile in main project repo ho ho ho evil
target_path = "../bin/"

if env["platform"] == "windows":
    library = env.SharedLibrary(
        target_path + "libgdexample{}{}".format(env["suffix"], env.subst("$SHLIBSUFFIX")),
        source=sources,
    )
elif env["platform"] == "linuxbsd" or env["platform"] == "linux":
    library = env.SharedLibrary(
        target_path + "libgdexample{}{}".format(env["suffix"], env.subst("$SHLIBSUFFIX")),
        source=sources,
    )
# hope this never happens
elif env["platform"] == "macos":
    library = env.SharedLibrary(
        target_path + "libgdexample.{}.{}.framework/libgdexample.{}.{}".format(
            env["platform"], env["target"], env["platform"], env["target"]
        ),
        source=sources,
    )

Default(library)
